services:
  - type: web
    name: attendance-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    rootDir: backend   # 👈 Tells Render to use /backend folder
    envVars:
      - key: DB_HOST
        value: your-db-host-here
      - key: DB_PORT
        value: your-db-port-here
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: your-db-password-here
      - key: DB_NAME
        value: railway
